version: '3.8'

services:
  app:
    build: .
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - DAMS
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: damsdatabase
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - DAMS

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - DAMS

volumes:
  db_data:
networks:
  DAMS:
